// <auto-generated />
using ConferenceManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ConferenceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503000000_AddUsuarioActivo")]
    partial class AddUsuarioActivo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
