// <auto-generated />
using System;
using ConferenceManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceManager.Models.AvisoUrgente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId", "Activo");

                    b.ToTable("avisos_urgentes", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Conferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArancelesTexto")
                        .HasColumnType("text");

                    b.Property<string>("BannerModo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("ContactoAdicional")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Borrador");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("FormularioInscripcionUrl")
                        .HasColumnType("text");

                    b.Property<string>("InformacionPago")
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("text");

                    b.Property<string>("Lema")
                        .HasColumnType("text");

                    b.Property<string>("LogoSecundarioUrl")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("MostrarContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("MostrarDescripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("MostrarFechas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("MostrarInscripciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("MostrarOrganizadores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text");

                    b.Property<string>("Tipografia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueDireccion")
                        .HasColumnType("text");

                    b.Property<string>("VenueLinkMaps")
                        .HasColumnType("text");

                    b.Property<string>("VenueNombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "Estado");

                    b.ToTable("conferencias", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.ConferenciaLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId");

                    b.HasIndex("ConferenciaId", "IsActive");

                    b.ToTable("conferencia_layouts", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.EjeTematico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId");

                    b.ToTable("ejes_tematicos", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Expositor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RedesSociales")
                        .HasColumnType("jsonb");

                    b.Property<string>("TokenAcceso")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId");

                    b.HasIndex("TokenAcceso")
                        .IsUnique();

                    b.ToTable("expositores", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.ExpositorCredencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExpositorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpositorId");

                    b.ToTable("ExpositorCredenciales");
                });

            modelBuilder.Entity("ConferenceManager.Models.FechaImportante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId");

                    b.ToTable("fechas_importantes", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.ImagenAlmacenada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<byte[]>("Datos")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UsuarioId");

                    b.ToTable("imagenes_almacenadas", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Organizador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId");

                    b.ToTable("organizadores", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("PuedeGenerarCertificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId", "Email")
                        .IsUnique();

                    b.ToTable("participantes", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("Revoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UsuarioId", "Revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Sala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId", "Nombre")
                        .IsUnique();

                    b.ToTable("salas", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.SeccionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BgColor")
                        .HasColumnType("text");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FontSize")
                        .HasColumnType("text");

                    b.Property<int?>("LogoAltura")
                        .HasColumnType("integer");

                    b.Property<int?>("LogoColumnas")
                        .HasColumnType("integer");

                    b.Property<int?>("PaddingV")
                        .HasColumnType("integer");

                    b.Property<string>("SeccionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextoColor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId", "SeccionKey")
                        .IsUnique();

                    b.ToTable("seccion_configs", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Sesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConferenciaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("EncuestaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ExpositorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("SalaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Track")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenciaId");

                    b.HasIndex("ExpositorId");

                    b.HasIndex("Fecha");

                    b.HasIndex("SalaId");

                    b.ToTable("sesiones", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("EmailVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Organizacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("VerificationToken");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.AvisoUrgente", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany()
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.Conferencia", b =>
                {
                    b.HasOne("ConferenceManager.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConferenceManager.Models.ConferenciaLayout", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany("Layouts")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.EjeTematico", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany("EjesTematicos")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.Expositor", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany()
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.ExpositorCredencial", b =>
                {
                    b.HasOne("ConferenceManager.Models.Expositor", "Expositor")
                        .WithMany()
                        .HasForeignKey("ExpositorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expositor");
                });

            modelBuilder.Entity("ConferenceManager.Models.FechaImportante", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany("FechasImportantes")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.Organizador", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany("Organizadores")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.Participante", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany()
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.RefreshToken", b =>
                {
                    b.HasOne("ConferenceManager.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConferenceManager.Models.Sala", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany()
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.SeccionConfig", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany("SeccionConfigs")
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");
                });

            modelBuilder.Entity("ConferenceManager.Models.Sesion", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia")
                        .WithMany()
                        .HasForeignKey("ConferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceManager.Models.Expositor", "Expositor")
                        .WithMany()
                        .HasForeignKey("ExpositorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceManager.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conferencia");

                    b.Navigation("Expositor");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ConferenceManager.Models.Conferencia", b =>
                {
                    b.Navigation("EjesTematicos");

                    b.Navigation("FechasImportantes");

                    b.Navigation("Layouts");

                    b.Navigation("Organizadores");

                    b.Navigation("SeccionConfigs");
                });

            modelBuilder.Entity("ConferenceManager.Models.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
