// <auto-generated />
using System;
using ConferenceManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501000001_AddExpositor")]
    partial class AddExpositor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceManager.Models.Conferencia", b => { });
            modelBuilder.Entity("ConferenceManager.Models.Expositor", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasDefaultValueSql("gen_random_uuid()");
                    b.Property<Guid>("ConferenciaId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("timestamptz").HasDefaultValueSql("NOW()");
                    b.Property<string>("Bio").HasColumnType("text");
                    b.Property<string>("Email").HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("FotoUrl").HasColumnType("text");
                    b.Property<string>("Nombre").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<string>("RedesSociales").HasColumnType("jsonb");
                    b.Property<string>("TokenAcceso").IsRequired().HasMaxLength(36).HasColumnType("character varying(36)");
                    b.HasKey("Id");
                    b.HasIndex("ConferenciaId");
                    b.HasIndex("TokenAcceso").IsUnique();
                    b.ToTable("expositores", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.Sala", b => { });
            modelBuilder.Entity("ConferenceManager.Models.RefreshToken", b => { });
            modelBuilder.Entity("ConferenceManager.Models.Usuario", b => { });

            modelBuilder.Entity("ConferenceManager.Models.Expositor", b =>
                {
                    b.HasOne("ConferenceManager.Models.Conferencia", "Conferencia").WithMany().HasForeignKey("ConferenciaId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Conferencia");
                });
#pragma warning restore 612, 618
        }
    }
}
