// <auto-generated />
using ConferenceManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ConferenceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503000001_AddImagenAlmacenada")]
    partial class AddImagenAlmacenada
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
