// <auto-generated />
using System;
using ConferenceManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ConferenceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510000000_AddExpositorCredencial")]
    partial class AddExpositorCredencial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasPostgresExtension("pgcrypto");

            modelBuilder.Entity("ConferenceManager.Models.ExpositorCredencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ExpositorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExpositorId")
                        .IsUnique();

                    b.ToTable("expositor_credenciales", (string)null);
                });

            modelBuilder.Entity("ConferenceManager.Models.ExpositorCredencial", b =>
                {
                    b.HasOne("ConferenceManager.Models.Expositor", "Expositor")
                        .WithOne()
                        .HasForeignKey("ConferenceManager.Models.ExpositorCredencial", "ExpositorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expositor");
                });
#pragma warning restore 612, 618
        }
    }
}
